### ISSUE TITLE
GP Atom Plugin not Working

### ISSUE THREAD

**Issue by hchawla1** [steveatkin/gp-atom-package#2]
If you install gp-atom plugin on Atom, you are not able to create bundle, download bundle, upload bundle or delete bundle.

For example, while downloading a bundle the errors I get are 
```
Error: getaddrinfo ENOTFOUND file file:80 at errnoException (dns.js:28:10) at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26) 
```

**Comment by hchawla1** [comment]
https://github.ibm.com/gp/gp-rest/issues/243

**Comment by hchawla1** [comment]
Scheme not set for Swagger #243

**Comment by hchawla1** [comment]
Scheme not set for Swagger

**Comment by hchawla1** [comment]
Fixed
